name: Deploy MERN to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Write SSH private key to file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Confirm SSH key is saved
        run: ls -l private_key.pem

      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key_path: private_key.pem
          script: echo "✅ GitHub Actions connected to EC2 successfully!"

      - name: Copy project files to EC2
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key_path: private_key.pem
          source: "."
          target: "/home/ubuntu/mern-app"
          debug: true

      - name: Restart backend with PM2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key_path: private_key.pem
          script: |
            cd /home/ubuntu/mern-app/backend
            npm install
            pm2 delete mern-backend || true
            pm2 start index.js --name mern-backend
