name: Deploy MERN App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Go to home directory
          cd ~

          # Clone the repo if not already cloned
          if [ ! -d "Mern-Fullstack-Project" ]; then
            git clone https://github.com/${{ github.repository }}.git Mern-Fullstack-Project
          else
            cd Mern-Fullstack-Project
            git pull origin main
          fi

          cd ~/Mern-Fullstack-Project

          # Backend
          cd backend
          npm install
          pm2 delete backend || true
          pm2 start index.js --name backend

          # Frontend
          cd ../frontend
          npm install
          npm run build
          pm2 delete frontend || true
          pm2 serve build 3000 --spa --name frontend
