name: Deploy to EC2

on:
  push:
    branches: [ ecs-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd Mern-Fullstack-Project
            git pull origin ecs-deploy
            echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" > .env
            docker compose down
            docker compose up -d --build
